### ISSUE TITLE
Is it possible to manually raise the video bitrate?

### ISSUE THREAD

**Issue by yuya-h-29** [aws-samples/amazon-ivs-broadcast-ios-sample#23]
Hi! Thank you for providing the amazing SDK and I'm grateful for your kind support!!
I have some questions about manipulating video bitrate. 

It's sort of picky (and apologize for that), but I need to handle live streams held with an unstable internet connection. While setting up the IVS broadcast session, I configured the `initial bitrate`, `max bitrate`, `target fps`, and `size` for the video setting. 
```
IVSBroadcastSession.applicationAudioSessionStrategy = .playAndRecord
let config = IVSBroadcastConfiguration()
try config.audio.setBitrate(128_000)
try config.video.setInitialBitrate(4_000_000)
try config.video.setMaxBitrate(8_500_000)
try config.video.setTargetFramerate(30)
try config.video.setSize(CGSize(width: 1920, height: 1080))
```

To handle the situation like a user stream with low bandwidth, I didn't set the `min bitrate`, so the live stream won't get disconnected even if the user streams with a temporally unstable internet connection. (since I didn't set the min, 300_000 is applied by default min bitrate). Since the broadcast SDK supports automatic bitrate adjustments, I manually change the network bandwidth from iPhone's developer setting and streamed for about 90 min, as below. However, after I lower the bandwidth and the video bitrate gets low, and then revert it to the original bandwidth (turn off the network conditioner), it takes a while to get back to high video bitrate. 

1. Start with disabling the network link conditioner and streamed for around 30 min -> the bitrate was around 4,000,000 to 8,500,000, which is great
2. Turned on the 2Mbps network link from the iPhone's developer setting for around 5 min -> the bitrate got low to around 1,00,000, which is also fine
3.  turned off the network link conditioner -> the video bitrate is steady with around 1,000,000 to 2,000,000 for around 30 min, then back to a higher bitrate. It's good that the bitrate recovers, but I want it to happen a little bit more quickly. (maybe like within 5 min or something?)

<img width="728" alt="Screen Shot 2022-09-13 at 23 32 23" src="https://user-images.githubusercontent.com/54800510/189939462-8276e57a-da25-4052-98f9-6f24a8cc24ff.png">

So I want to confirm things below

1. Even after the network condition gets better, the automatic bitrate adjustments take a while to recover the bitrate?
2. Is this an expected behavior? 
3. Is there a way to raise the bitrate a little bit more quickly?
5. While the video bitrate is low, I want to tell the user something like "the streaming video might get pixelated due to the lower bitrate". Is there a way to check the current video bitrate out? I checked the IVS broadcast document and I think [broadcastQualityChanged](https://aws.github.io/amazon-ivs-broadcast-docs/1.5.0/ios/Protocols/IVSBroadcastSessionDelegate.html#/c:objc(pl)IVSBroadcastSessionDelegate(im)broadcastSession:broadcastQualityChanged:) can be used, but I saw it returns one of the following values, 0.0, 0.25, 0.5, 0.75 while I was testing. With low video bitrate, like around 1,000,000 (I think) it takes a while to get 0.25+ after getting 0.0. So it would be better, if I can find out the current video bitrate or the way to raise the bitrate if the network connection gets recovered. 

Again, so sorry for the picky question, and thank you so much for the support!!
(I hope all users use wired connections while broadcast... 😅)

**Comment by bclymer** [comment]
@yuya-h-29 hello, thank you for the detailed issue. I have good news!

I'll answer your 4 questions for v1.5.2 (the latest available today), and then again for an upcoming release.
### For 1.5.2
1. It takes a while to recover, the bitrate increase is gradual to prevent congestion and starvation.
2. Yes it is expected.
3. There is not a way to increase the recovery rate.
4. That API (`broadcastQualityChanged`) is the best way to display a message like that today.

### For Upcoming Release
1. It will still be expected that recovery takes time, we do not do bandwidth estimation to make large bitrate jumps, only gradual increases.
2. Same answer as 1.5.2
3. There will be a new API that controls bitrate recovery aggressiveness. Today it takes ~4.5 minutes to double the bitrate after dropping due to low bandwidth, with the new API it can be as low as 36 seconds if the network is strong. So recovery can be ~8x faster.
4. A new API will be introduced that allows monitoring the outgoing bitrate directly. More details will be in the release notes and updated API reference documentation.

I can not confirm a release date for the upcoming release, but keep an eye on our [Release Notes](https://docs.aws.amazon.com/ivs/latest/userguide/release-notes.html) page for details. I will try my best to remember to comment on this issue again when we release.

**Comment by yuya-h-29** [comment]
@bclymer 
Thank you so much for the quick response and detailed explanation, Brian!! 
Looking for the board cast SDK get updated soon :)

**Comment by bclymer** [comment]
Hey @yuya-h-29 good news, 1.7.0 has been released today with the new APIs I was talking about.

Here is [autoBitrateProfile](https://aws.github.io/amazon-ivs-broadcast-docs/1.7.0/ios/Classes/IVSVideoConfiguration.html#/c:objc(cs)IVSVideoConfiguration(py)autoBitrateProfile), and here is [transmissionStatisticsChanged:](https://aws.github.io/amazon-ivs-broadcast-docs/1.7.0/ios/Protocols/IVSBroadcastSessionDelegate.html#/c:objc(pl)IVSBroadcastSessionDelegate(im)broadcastSession:transmissionStatisticsChanged:). I hope those help out your use case!

You can view the full release notes [here](https://docs.aws.amazon.com/ivs/latest/userguide/release-notes.html).
